#
# Copyright 2025 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#

name: Setup xcresultparser tool (iOS)

runs:
  using: "composite"
  steps:
    # Composite actions do not support variables at the workflow definition level.
    # Workaround: Set the workflow environment variables in a separate step.
    # 344eeaffd876b6c70da56d057fabb018de464773 (v1.8.4) SHA for https://github.com/a7ex/xcresultparser/releases/tag/1.8.4
    - name: Set workflow vars
      id: vars
      shell: bash
      run: |
        echo "XCRESULTPARSER_COMMIT_SHA=344eeaffd876b6c70da56d057fabb018de464773" >> "${GITHUB_OUTPUT}"

    # Cache xcresultparser binary
    - name: Cache xcresultparser binary
      id: cache-xcresultparser
      uses: actions/cache@v4.2.1
      with:
        path: ~/.xcresultparser
        key: xcresultparser-${{ runner.os }}-commitSHA-${{ steps.vars.outputs.XCRESULTPARSER_COMMIT_SHA }}
        
    # Checkout the xcresultparser tool source code using the commit SHA
    - name: Checkout xcresultparser
      if: steps.cache-xcresultparser.outputs.cache-hit != 'true'
      uses: actions/checkout@v4.2.2
      with:
        repository: 'a7ex/xcresultparser'
        ref: ${{ steps.vars.outputs.XCRESULTPARSER_COMMIT_SHA }}
        path: './xcresultparser-src'

    # Build xcresultparser from source
    - name: Build xcresultparser
      if: steps.cache-xcresultparser.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd ./xcresultparser-src
        swift build -c release
        mkdir -p ~/.xcresultparser
        cp .build/release/xcresultparser ~/.xcresultparser/xcresultparser

    # Make xcresultparser available globally
    - name: Add xcresultparser to PATH
      shell: bash
      run: |
        chmod +x ~/.xcresultparser/xcresultparser
        echo "$HOME/.xcresultparser" >> $GITHUB_PATH