name: 'Cache aepsdk-commons scripts'
description: 'Simplifies caching for the aepsdk-commons scripts by handling cache restore and updating automatically.'

inputs:
  workflow_tag:
    description: 'The tag or ref of the reusable workflow being invoked (ex: gha-ios-1.0.0, gha-android-1.0.0).'
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore cached scripts from aepsdk-commons
      id: cache-scripts
      uses: actions/cache@v4.1.1
      with:
        path: .github/aepsdk-commons/scripts
        key: aepsdk-commons-${{ inputs.workflow_tag }} # Cache key format: <REPO_NAME>-<TAG>

    - name: Download scripts from aepsdk-commons
      if: steps.cache-scripts.outputs.cache-hit != 'true'
      uses: actions/checkout@v4.1.7
      with:
        repository: adobe/aepsdk-commons
        ref: ${{ inputs.workflow_tag }}
        path: .github/aepsdk-commons
        sparse-checkout: 'scripts' # Only checkout the scripts directory

    - uses: actions/cache/save@v4.1.1
      with:
        path: .github/aepsdk-commons/scripts
        key: aepsdk-commons-${{ inputs.workflow_tag }} # Cache key format: <REPO_NAME>-<TAG>
