#
# Copyright 2024 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#

name: Publish Release (Android)

# This workflow relies on the following secrets:
# - GITHUB_TOKEN: Required for creating a release on GitHub
# - GPG_SECRET_KEYS
# - GPG_OWNERTRUST
# - SONATYPE_USERNAME
# - SONATYPE_PASSWORD
# These can be passed using the `secrets: inherit` option in the caller workflow file.

on: 
  workflow_call:
    inputs:
      tag:
        description: |
          The tag (version) to be released (ex: 1.2.3). The workflow will automatically prepend the "v" prefix, resulting in a tag like "v1.2.3".
        type: string
        required: true

      create-github-release:
        description: |
          Boolean flag that determines whether to create a GitHub release. If the specified `tag` does not exist, it will be created.
        type: boolean
        required: true
        default: true

      release-variant:
        description: | 
          The variant used to control the GitHub release title suffix and Maven publish command (ex: core -> v3.2.1-core & make core-publish-main). 
          If not specified, uses the default values for both.
        type: string
        required: false
        default: ''

      version-validation-paths:
        description: |
          A comma-separated list of absolute and/or relative file paths to validate. 
          Each path can optionally specify a pattern type using the syntax:
          
          **Syntax:** `path[:file_type]`

          **Example:**
          `"code/edge/src/main/java/com/adobe/marketing/mobile/EdgeConstants.java, code/gradle.properties"`

          This argument is required.
        type: string
        required: true

      version-validation-dependencies:
        description: |
          A comma-separated list of dependencies with their versions. 
          Each dependency can optionally specify a semicolon-separated list of the file paths where it applies using the `@` symbol.
          
          **Syntax:** `<name> <version>[@file_path1[;file_path2;...]]`

          - If the `@` syntax is used, the dependency will only apply to the specified files.
          - If the `@` symbol is omitted, the dependency applies to all relevant files.
          - When specifying custom file paths, you must provide either an absolute or relative path to each file.
          - If a dependency is missing a version, it will be skipped.

          **Example:**
          `"Core 7.8.9, EdgeIdentity 8.9.10@code/gradle.properties;code/Constants.kt"`
        type: string
        required: false
        default: ''

      workflow_tag:
        description: 'The tag or ref of the reusable workflow being invoked (ex: gha-android-1.2.3).'
        type: string
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      
      - name: Restore cached scripts from aepsdk-commons
        id: cache-scripts
        uses: actions/cache@v4.1.2
        with:
          path: .github/aepsdk-commons/scripts
          key: aepsdk-commons-${{ inputs.workflow_tag }} # Cache key format: <REPO_NAME>-<TAG>

      - name: Download scripts from aepsdk-commons
        if: steps.cache-scripts.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.7
        with:
          repository: adobe/aepsdk-commons
          ref: ${{ inputs.workflow_tag }}
          path: .github/aepsdk-commons
          sparse-checkout: 'scripts' # Only checkout the scripts directory

      - uses: actions/cache/save@v4.1.2
        if: steps.cache-scripts.outputs.cache-hit != 'true'
        with:
          path: .github/aepsdk-commons/scripts
          key: aepsdk-commons-${{ inputs.workflow_tag }} # Cache key format: <REPO_NAME>-<TAG>
        
      - name: Validate versions
        run: |
          set -eo pipefail
          echo Release version: ${{ github.event.inputs.tag }}
          python3 ./.github/aepsdk-commons/scripts/versions.py \
            -v "${{ github.event.inputs.tag }}" \
            -p "${{ inputs.version-validation-paths }}" \
            -d "${{ inputs.version-validation-dependencies }}"

      - name: Remove scripts from aepsdk-commons
        run: rm -rf .github/aepsdk-commons

      - name: Create GitHub release
        if: ${{ inputs.create-github-release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Initialize the title with the tag
          TITLE="v${{ github.event.inputs.tag }}"

          # Append suffix if provided (non-empty)
          if [ -n "${{ inputs.release-variant }}" ]; then
            TITLE="${TITLE}-${{ inputs.release-variant }}"
          fi

          # Create the GitHub release with the constructed title
          gh release create "v${{ github.event.inputs.tag }}" \
            --generate-notes \
            --title "${TITLE}"

      - name: Import GPG key
        env:
          GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
          GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
        run: |
          echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch --yes
          echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust --no-tty --batch --yes

      - name: Publish to Maven Central Repository
        run: |
          if [ -n "${{ inputs.release-variant }}" ]; then
            make "${{ inputs.release-variant }}-publish-main"
          else
            make ci-publish
          fi
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}