#
# Copyright 2023 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#

name: BOM Release  
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '*android/aepsdk-bom/sdk-bom/bom.properties'

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Set up Java
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v4.2.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Import GPG key
        env:
          GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
          GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
        run: |
          echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch --yes
          echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust --no-tty --batch --yes

      - name: Publish sdk-bom to maven central
        run: make -C android/aepsdk-bom bom-publish-main
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Read bomVersion from gradle.properties
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './android/aepsdk-bom/gradle.properties'
          properties: 'bomVersion'

      - name: BOM version
        run: echo ${{ steps.read_property.outputs.bomVersion }}

      - name: Create GitHub release
        continue-on-error: true # Ignore "release already exists" errors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="bom-${{ steps.read_property.outputs.bomVersion }}"
          gh release create "$TAG" \
            --title "$TAG" \
            --generate-notes
          
      - name: Update Release page
        run: |
          gh release edit bom-${{ steps.read_property.outputs.bomVersion }} --repo adobe/aepsdk-commons --notes-file ./android/aepsdk-bom/sdk-bom/bom-release-notes.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
