name: Build and Test (iOS)

on:
  workflow_call:
    inputs:
      device_name:
        required: true
        type: string
      os_version:
        required: true
        type: string
      github_ref:
        required: true
        type: string
      # Flags for jobs to run
      run_test_ios_unit:
        required: false
        type: boolean
        default: true
      run_test_ios_functional:
        required: false
        type: boolean
        default: true
      run_test_ios_integration:
        required: false
        type: boolean
        default: true
      run_test_tvos_unit:
        required: false
        type: boolean
        default: true
      run_test_tvos_functional:
        required: false
        type: boolean
        default: true
      run_build_xcframework_and_app:
        required: false
        type: boolean
        default: true

      workflow_tag:
        description: 'The tag or ref of the reusable workflow being invoked (ex: gha-ios-1.0.0).'
        type: string
        required: true

jobs:
  validate-code:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Restore cached actions from aepsdk-commons
        id: cache-commons
        uses: actions/cache@v4.1.1
        with:
          path: .github/aepsdk-commons/.github/actions
          key: aepsdk-commons-${{ inputs.workflow_tag }} # Cache key format: <REPO_NAME>-<TAG>

      - name: Download actions from aepsdk-commons
        if: steps.cache-commons.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.2.2
        with:
          repository: adobe/aepsdk-commons
          ref: ${{ inputs.workflow_tag }}
          path: .github/aepsdk-commons
          sparse-checkout: '.github/actions' # Only checkout the GitHub actions directory

      - uses: actions/cache/save@v4.1.1
        if: steps.cache-commons.outputs.cache-hit != 'true'
        with:
          path: .github/aepsdk-commons/.github/actions
          key: aepsdk-commons-${{ inputs.workflow_tag }} # Cache key format: <REPO_NAME>-<TAG>

      - name: Setup Dependencies
        uses: ./.github/aepsdk-commons/.github/actions/setup-action

      - name: Remove files from aepsdk-commons
        run: rm -rf ./github/aepsdk-commons

      - name: Lint Source Code
        run: make lint

  test-ios-unit:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run_test_ios_unit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Restore cached scripts from aepsdk-commons
        id: cache-scripts
        uses: actions/cache@v4.1.1
        with:
          path: .github/aepsdk-commons/scripts
          key: aepsdk-commons-${{ inputs.workflow_tag }} # Cache key format: <REPO_NAME>-<TAG>

      - name: Download actions from aepsdk-commons
        uses: actions/checkout@v4.2.2
        with:
          repository: adobe/aepsdk-commons
          ref: main
          path: .github/aepsdk-commons
          sparse-checkout: '.github/actions' # Only checkout the GitHub actions directory

      - name: Setup Dependencies
        uses: ./.github/aepsdk-commons/.github/actions/setup-action

      - name: Remove files from aepsdk-commons
        run: rm -rf ./github/aepsdk-commons

      - name: Run iOS Unit Tests
        run: make unit-test-ios

  test-ios-functional:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run_test_ios_functional

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Checkout actions from aepsdk-commons
        uses: actions/checkout@v4.2.2
        with:
          repository: adobe/aepsdk-commons
          ref: main
          path: .github/aepsdk-commons
          sparse-checkout: '.github/actions' # Only checkout the GitHub actions directory

      - name: Setup Dependencies
        uses: ./.github/aepsdk-commons/.github/actions/setup-action

      - name: Remove files from aepsdk-commons
        run: rm -rf ./github/aepsdk-commons

      - name: Run iOS Functional Tests
        run: make functional-test-ios

  test-ios-integration:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run_test_ios_integration && (inputs.github_ref == 'refs/heads/main' || inputs.github_ref == 'refs/heads/staging')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Checkout actions from aepsdk-commons
        uses: actions/checkout@v4.2.2
        with:
          repository: adobe/aepsdk-commons
          ref: main
          path: .github/aepsdk-commons
          sparse-checkout: '.github/actions' # Only checkout the GitHub actions directory

      - name: Setup Dependencies
        uses: ./.github/aepsdk-commons/.github/actions/setup-action

      - name: Remove files from aepsdk-commons
        run: rm -rf ./github/aepsdk-commons

      - name: Run iOS Integration Tests
        run: make test-integration-upstream

  test-tvos-unit:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run_test_tvos_unit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Checkout actions from aepsdk-commons
        uses: actions/checkout@v4.2.2
        with:
          repository: adobe/aepsdk-commons
          ref: main
          path: .github/aepsdk-commons
          sparse-checkout: '.github/actions' # Only checkout the GitHub actions directory

      - name: Setup Dependencies
        uses: ./.github/aepsdk-commons/.github/actions/setup-action

      - name: Remove files from aepsdk-commons
        run: rm -rf ./github/aepsdk-commons
      
      - name: Run tvOS Unit Tests
        run: make unit-test-tvos

  test-tvos-functional:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run_test_tvos_functional

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Checkout actions from aepsdk-commons
        uses: actions/checkout@v4.2.2
        with:
          repository: adobe/aepsdk-commons
          ref: main
          path: .github/aepsdk-commons
          sparse-checkout: '.github/actions' # Only checkout the GitHub actions directory

      - name: Setup Dependencies
        uses: ./.github/aepsdk-commons/.github/actions/setup-action

      - name: Remove files from aepsdk-commons
        run: rm -rf ./github/aepsdk-commons

      - name: Run tvOS Functional Tests
        run: make functional-test-tvos

  build_xcframework_and_app:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run_build_xcframework_and_app && (inputs.github_ref == 'refs/heads/main' || inputs.github_ref == 'refs/heads/staging')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Checkout actions from aepsdk-commons
        uses: actions/checkout@v4.2.2
        with:
          repository: adobe/aepsdk-commons
          ref: main
          path: .github/aepsdk-commons
          sparse-checkout: '.github/actions' # Only checkout the GitHub actions directory

      - name: Setup Dependencies
        uses: ./.github/aepsdk-commons/.github/actions/setup-action

      - name: Remove files from aepsdk-commons
        run: rm -rf ./github/aepsdk-commons

      - name: Build XCFramework
        run: make archive

      - name: Build Test App
        run: make build-app
