name: Build and Test (iOS)

on:
  workflow_call:
    inputs:
      device-name:
        required: true
        type: string
      os-version:
        required: true
        type: string
      # Flags for jobs to run
      run-test-ios-unit:
        required: false
        type: boolean
        default: true
      run-test-ios-functional:
        required: false
        type: boolean
        default: true
      run-test-ios-integration:
        required: false
        type: boolean
        default: true
      run-test-tvos-unit:
        required: false
        type: boolean
        default: true
      run-test-tvos-functional:
        required: false
        type: boolean
        default: true
      run-build-xcframework-and-app:
        required: false
        type: boolean
        default: true

jobs:
  validate-code:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@gha-1.0.0

      - name: Lint Source Code
        run: make lint

  test-ios-unit:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run-test-ios-unit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@gha-1.0.0

      - name: Run iOS Unit Tests
        run: make unit-test-ios

  test-ios-functional:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run-test-ios-functional

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@gha-1.0.0

      - name: Run iOS Functional Tests
        run: make functional-test-ios

  test-ios-integration:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run-test-ios-integration && (${{ github.ref }} == 'refs/heads/main' || ${{ github.ref }} == 'refs/heads/staging')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@gha-1.0.0

      - name: Run iOS Integration Tests
        run: make test-integration-upstream

  test-tvos-unit:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run-test-tvos-unit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@gha-1.0.0
      
      - name: Run tvOS Unit Tests
        run: make unit-test-tvos

  test-tvos-functional:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run-test-tvos-functional

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@gha-1.0.0

      - name: Run tvOS Functional Tests
        run: make functional-test-tvos

  build_xcframework_and_app:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.run-build-xcframework-and-app && (${{ github.ref }} == 'refs/heads/main' || ${{ github.ref }} == 'refs/heads/staging')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@gha-1.0.0

      - name: Build XCFramework
        run: make archive

      - name: Build Test App
        run: make build-app
