name: Reusable Build and Test (iOS)

on:
  workflow_call:
    inputs:
      device_name:
        required: true
        type: string
      os_version:
        required: true
        type: string
      github_ref:
        required: true
        type: string

jobs:
  validate-code:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
      - name: Setup Dependencies
        uses: ./.github/actions/setup-action

      - name: Lint Source Code
        run: make lint

  test-ios-unit:
    runs-on: macos-latest
    needs: validate-code

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Setup Dependencies
        uses: ./.github/actions/setup-action

      - name: Run iOS Unit Tests
        run: make unit-test-ios

  test-ios-functional:
    runs-on: macos-latest
    needs: validate-code

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
      - name: Setup Dependencies
        uses: ./.github/actions/setup-action

      - name: Run iOS Functional Tests
        run: make functional-test-ios

  test-ios-integration:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.github_ref == 'refs/heads/main' || inputs.github_ref == 'refs/heads/staging'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
      - name: Setup Dependencies
        uses: ./.github/actions/setup-action
      - name: Run iOS Integration Tests
        run: make test-integration-upstream

  test-tvos-unit:
    runs-on: macos-latest
    needs: validate-code

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
      - name: Setup Dependencies
        uses: ./.github/actions/setup-action


      - name: Run tvOS Unit Tests
        run: make unit-test-tvos

  test-tvos-functional:
    runs-on: macos-latest
    needs: validate-code

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
      - name: Setup Dependencies
        uses: ./.github/actions/setup-action

      - name: Run tvOS Functional Tests
        run: make functional-test-tvos

  build_xcframework_and_app:
    runs-on: macos-latest
    needs: validate-code
    if: inputs.github_ref == 'refs/heads/main' || inputs.github_ref == 'refs/heads/staging'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
      - name: Setup Dependencies
        uses: ./.github/actions/setup-action

      - name: Build XCFramework
        run: make archive

      - name: Build Test App
        run: make build-app
