name: Custom Command Build and Test (iOS)

on:
  workflow_call:
    inputs:
      device-names:
        type: string
        required: true
      os-versions:
        type: string
        required: true
      command:
        type: string
        required: true
      run-validate-code:
        type: boolean
        default: false

jobs:
  validate-code:
    runs-on: macos-latest
    if: ${{ inputs.run-validate-code }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@ios-circleci-to-github

      - name: Lint Source Code
        run: make lint

  custom-command:
    runs-on: macos-latest
    needs: validate-code
    strategy:
      matrix:
        device: ${{ fromJson(inputs.device-names) }}
        os: ${{ fromJson(inputs.os-versions) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@ios-circleci-to-github

      - name: Run ${{ inputs.command }}
        run: ${{ inputs.command }}
  
  custom-command-no-validate:
    runs-on: macos-latest
    if: ${{ inputs.run-validate-code == false }}
    strategy:
      matrix:
        device: ${{ fromJson(inputs.device-names) }}
        os: ${{ fromJson(inputs.os-versions) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Dependencies
        uses: timkimadobe/aepsdk-commons/.github/actions/ios-setup-dependencies-action@ios-circleci-to-github

      - name: Run ${{ inputs.command }}
        run: ${{ inputs.command }}
