name: Custom Build and Test (iOS)

on:
  workflow_call:
    inputs:
      device_name:
        required: true
        type: string
      os_version:
        required: true
        type: string
      github_ref:
        required: true
        type: string
      command:
        required: true
        type: string

jobs:
  validate-code:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Checkout actions from aepsdk-commons
        uses: actions/checkout@v4.1.7
        with:
          repository: timkimadobe/aepsdk-commons
          ref: ios-reusable-workflows
          path: .github/aepsdk-commons
          sparse-checkout: '.github/actions' # Only checkout the GitHub actions directory

      - name: Setup Dependencies
        uses: ./.github/aepsdk-commons/.github/actions/setup-action

      - name: Remove files from aepsdk-commons
        run: rm -rf ./github/aepsdk-commons

      - name: Lint Source Code
        run: make lint

  custom-command:
    runs-on: macos-latest
    needs: validate-code

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Checkout actions from aepsdk-commons
        uses: actions/checkout@v4.1.7
        with:
          repository: timkimadobe/aepsdk-commons
          ref: ios-reusable-workflows
          path: .github/aepsdk-commons
          sparse-checkout: '.github/actions' # Only checkout the GitHub actions directory

      - name: Setup Dependencies
        uses: ./.github/aepsdk-commons/.github/actions/setup-action

      - name: Remove files from aepsdk-commons
        run: rm -rf ./github/aepsdk-commons

      - name: Run Custom Command
        run: ${{ inputs.command }}
