#
# Copyright 2024 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#

name: Release (iOS)

# Currently this workflow relies on two secrets:
# - GITHUB_TOKEN: Required for creating a release on GitHub
# - COCOAPODS_TRUNK_TOKEN: Required for pushing a pod to Cocoapods
# These can be passed using the `secrets: inherit` option in the caller workflow file.

on:
  workflow_call:
    inputs:
      tag:
        description: 'Existing tag (version) being released (ex: 5.0.1)'
        required: true
        type: string

      # current idea for all of these inputs: comma separated extension names: AEPServices, AEPCore, AEPRulesEngine
      full_release_extensions:
        description: 'Run full release process: SPM and podspec validation, build artifacts, GH release (`false` to only check podspec version)'
        required: true
        default: ''
        type: string

      extension_dependencies:
        description: 'For extension dependencies whose frameworks should be included in the release, but their version fetched from the pods'
        required: false
        default: ''
        type: string

      pod_release_extensions:
        description: 'Release to Cocoapods (`false` to skip)'
        required: true
        default: ''
        type: string

jobs:
  release:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        ref: main
    
    - name: Set up Xcode Version
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '15.0.1'

    - name: Install Cocoapods
      run: gem install cocoapods

    - name: Install XcodeGen
      run: brew install xcodegen

      # this is NOT conditional when you run the release script.... and it uses a makefile rule which means it is already 
      # agnostic to whatever setup the repo has - it's up to the repo maintainer to define their makefile rule for make check-verison
    - name: Check Version in Podspec 
      run: |
        set -eo pipefail
        echo Target version: ${{ inputs.tag }}
        make check-version VERSION=${{ inputs.tag }}

    - name: Pod repo update
      if: ${{ inputs.full_release_extensions != '' }}
      run: | 
        pod repo update

    - name: SPM Integration Test
      if: ${{ inputs.full_release_extensions != '' }}
      run: |
        set -eo pipefail
        echo SPM integration test starts:
        make test-SPM-integration

    - name: Podspec File Verification
      if: ${{ inputs.full_release_extensions != '' }}
      run: |
        set -eo pipefail
        echo podspec file verification starts:
        make test-podspec
        
    - name: Build Artifacts
      if: ${{ inputs.full_release_extensions != '' }}
      run: |
        make archive
        make zip
    
    # INSERT dependency version fetching step here

    # - name: Create GH Release and Upload Asset - ${{ inputs.library_name }}
    #   if: ${{ inputs.full_release_extensions }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     gh release create ${{ inputs.tag }} \
    #       --verify-tag \
    #       --generate-notes \
    #       --title "v${{ inputs.tag }}" \
    #       ./build/${{ inputs.library_name }}.xcframework.zip#${{ inputs.library_name }}-${{ inputs.tag }}.xcframework.zip

    - name: Create GH Release and Upload Assets
      if: ${{ inputs.full_release_extensions != '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FULL_RELEASE_EXTENSIONS: ${{ github.event.inputs.full_release_extensions }}
        EXTENSION_DEPENDENCIES: ${{ github.event.inputs.extension_dependencies }}
        TAG: ${{ github.event.inputs.tag }}
      run: |
        set -eo pipefail

        # Initialize an empty string to collect the file arguments
        FILE_ARGS=""
        
        # Process FULL_RELEASE_EXTENSIONS
        # Split the input string into an array using comma as delimiter
        IFS=',' read -ra LIBS <<< "${FULL_RELEASE_EXTENSIONS}"
        for LIB in "${LIBS[@]}"; do
          # Trim whitespace from the library name
          LIB=$(echo "$LIB" | xargs)
          # Append the file argument to FILE_ARGS
          FILE_ARGS="$FILE_ARGS ./build/${LIB}.xcframework.zip#${LIB}-${TAG}.xcframework.zip"
        done

        # Process EXTENSION_DEPENDENCIES
        if [ -n "${EXTENSION_DEPENDENCIES}" ]; then
          # Split the input string into an array using comma as delimiter
          IFS=',' read -ra DEPS <<< "${EXTENSION_DEPENDENCIES}"
          # Loop over each dependency
          for DEP in "${DEPS[@]}"; do
            # Trim whitespace from the dependency name
            DEP=$(echo "$DEP" | xargs)
            echo "Processing dependency: $DEP"

            # Fetch version from podspec
            echo "Fetching version for dependency ${DEP}..."
            DEP_VERSION=$(pod spec cat "${DEP}" | jq -r '.version')
            echo "Fetched version for ${DEP}: ${DEP_VERSION}"

            # Append the file argument to FILE_ARGS
            FILE_ARGS="$FILE_ARGS ./build/${DEP}.xcframework.zip#${DEP}-${DEP_VERSION}.xcframework.zip"
          done
        fi

        # Now execute the gh release create command with all file arguments
        gh release create "$TAG" \
          --verify-tag \
          --generate-notes \
          --title "v$TAG" \
          $FILE_ARGS

    # - name: Publish Pods - ${{ inputs.library_name }}
    #   if: ${{ inputs.pod_release_extensions }}
    #   run: |
    #     set -eo pipefail
    #     pod trunk push ${{ inputs.library_name }}.podspec --allow-warnings --synchronous
    #     pod repo update
    #   env:
    #     COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

        # need to try running this with args, without the pod trunk and token requirements just to see if the
        # args are being populated correctly
    - name: Publish Pods
      if: ${{ inputs.pod_release_extensions != '' }}
      env:
        POD_RELEASE_EXTENSIONS: ${{ github.event.inputs.pod_release_extensions }}
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        set -eo pipefail
        # Split the input string into an array using comma as delimiter
        IFS=',' read -ra LIBS <<< "${POD_RELEASE_EXTENSIONS}"
        # Loop over each library name
        for LIB in "${LIBS[@]}"; do
          # Trim whitespace from the library name
          LIB=$(echo "$LIB" | xargs)
          # Publish the pod
          pod trunk push "${LIB}.podspec" --allow-warnings --synchronous
          pod repo update
        done
      
