name: testing
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ./github/workflows

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './android/aepsdk-bom/gradle.properties'
          properties: 'bomVersion'
      - name: Do something with your bumped release version
        run: echo ${{ steps.read_property.outputs.bomVersion }}

      - name: Create GH Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          name: bom-${{ steps.read_property.outputs.bomVersion }}
          tag: bom-${{ steps.read_property.outputs.bomVersion }}
          version: bom-${{ steps.read_property.outputs.bomVersion }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
